name: Python application

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install build tools (setuptools and distutils)
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-setuptools python3-distutils

    - name: Install dependencies
      run: make install

    - name: Run the application
      run: |
        make run &
        sleep 10  # Sleep for 10 seconds to allow the server to start

    - name: Test if the server is running
      run: curl http://localhost:3000