name: Python application

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Explicitly set Python 3.12

    # Install pip upgrade and setuptools/distutils via pip
    - name: Install pip, setuptools, and distutils
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install --upgrade wheel

    - name: Install dependencies
      run: make install

    - name: Run the application
      run: |
        make run &
        sleep 10  # Sleep for 10 seconds to allow the server to start

    - name: Test if the server is running
      run: curl http://localhost:3000
