name: Python application

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install distutils
      run: sudo apt-get update && sudo apt-get install python3-distutils

    - name: Install dependencies
      run: make install

    - name: Run the application
      run: make run &
        sleep 10  # Wait for the server to start

    - name: Test the server
      run: curl http://localhost:3000